"project_identifier" : "r7-labs-dnn-platform"
"base_path" : "./_src/Dnn.Platform/"
"preserve_hierarchy": true

files: [
  {
    "source" : "/**/*.resx",
    "translation" : "/%original_path%/%file_name%.%locale%.%file_extension%",
    "translation_replace": {
      ".en-US.ru-RU" : ".ru-RU"
    },
    "ignore": [
      "DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.*.resx",
      "DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.*.resx",
      "DNN Platform/Tests/DotNetNuke.Tests.Data/DataResources.resx",
      "DNN Platform/Website/App_GlobalResources/List_Country.resx"
    ]
  }
]
